### ISSUE TITLE
No need to include cdpId in flash loan data

### ISSUE THREAD

**Issue by therealmonoloco** [mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC#9]
https://github.com/mil0xeth/Strategy-Maker-lev-GUNIV3DAIUSDC/blob/1c0cb03f2313c9becd64ff6b6c25ab39a9d38370/contracts/Strategy.sol#L360

I can't think of any scenario where the strategy would need to perform actions over another cdp, so maybe it could be removed and instead trust on the strategy's `cdpId` variable.

**Comment by mil0xeth** [comment]
Unfortunately, it's necessary to supply the cdpId encoded into the data sent to the flashloan as the callback function from the flashloan is calling the _wind and _unwind functions from the library. Since a library can only access state variables from the calling contract if they are explicitly supplied, the variable is explicitly supplied through the decoding of the data attachment.
